/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk.makost.form;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author dF
 */
public class ManajemenKamar extends javax.swing.JPanel {

    /**
     * Creates new form ManajemenKamar
     */
    public ManajemenKamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apk/makost/icon/manajemen (1).png"))); // NOI18N
        jLabel2.setText("M Kamar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1100, 710));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
