/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk.makost.form;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Base64;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Profil extends javax.swing.JPanel {
private String username, foto;
private String filename;

    /**
     * Creates new form Profil
     */
    public Profil() {
        initComponents();
        refreshData();
        
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }
   
  
    public void refreshData(){
    try{
            java.sql.Connection conn = (Connection)apk.makost.koneksi.Koneksi.configDB();
            Statement s = conn.createStatement();
            String sql = ("Select * from tbl_user where username = '" + apk.makost.main.Login.txtusernamelogin.getText() + "'");
            ResultSet rs = s.executeQuery(sql);
            if(rs.next()){
                txtiduser.setText(rs.getString(1));
                txtun.setText(rs.getString(2));
                txtpw.setText(rs.getString(3));
                txtnadep.setText(rs.getString(4));
                txtnabel.setText(rs.getString(5));
                txthewan.setText(rs.getString(6));
                txtalamat.setText(rs.getString(13));
                txthobi.setText(rs.getString(12));
                txtnik.setText(rs.getString(11));
                txtemail.setText(rs.getString(8));
                txtnotelp.setText(rs.getString(7));
                txttgllahir.setText(rs.getString(9));
                txtjabatan.setText(rs.getString(10));
//                ImageIcon icon = new ImageIcon(
//               Objects.requireNonNull(this.getClass().getResource("src/upload/"+rs.getString("foto"))));
//               Image image = icon.getImage().getScaledInstance(labelfoto.getWidth(), labelfoto.getHeight(), Image.SCALE_SMOOTH);
//               ImageIcon ic = new ImageIcon(image);
//               labelfoto.setIcon(ic);

            }else{
                JOptionPane.showMessageDialog(null, username);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void refreshFoto(){
 // Memeriksa apakah dimensi label tidak nol
        File f = new File(this.foto);
        ImageIcon icon = new ImageIcon(f.toString());
        Image img = icon.getImage().getScaledInstance(labelfoto.getWidth(), labelfoto.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon ic = new ImageIcon(img);
        labelfoto.setIcon(ic);  
        this.filename = f.getAbsolutePath();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtiduser = new apk.makost.swing.TextField();
        txtun = new apk.makost.swing.TextField();
        txtpw = new apk.makost.swing.TextField();
        txtnadep = new apk.makost.swing.TextField();
        txtnabel = new apk.makost.swing.TextField();
        txthewan = new apk.makost.swing.TextField();
        txtalamat = new apk.makost.swing.TextField();
        txthobi = new apk.makost.swing.TextField();
        txtnik = new apk.makost.swing.TextField();
        txtemail = new apk.makost.swing.TextField();
        txtnotelp = new apk.makost.swing.TextField();
        txttgllahir = new apk.makost.swing.TextField();
        txtjabatan = new apk.makost.swing.TextField();
        btnpilihfoto = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        labelfoto = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(236, 243, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtiduser.setLabelText("ID User");
        txtiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiduserActionPerformed(evt);
            }
        });
        jPanel1.add(txtiduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 26, 255, -1));

        txtun.setLabelText("Username");
        jPanel1.add(txtun, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 88, 255, -1));

        txtpw.setLabelText("Password");
        jPanel1.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 152, 255, -1));

        txtnadep.setLabelText("Nama Depan");
        jPanel1.add(txtnadep, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 214, 255, -1));

        txtnabel.setLabelText("Nama Belakang");
        jPanel1.add(txtnabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 276, 255, -1));

        txthewan.setLabelText("Nama Hewan");
        jPanel1.add(txthewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 341, 255, -1));

        txtalamat.setLabelText("Alamat");
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 403, 553, 60));

        txthobi.setLabelText("Hobi");
        jPanel1.add(txthobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 26, 230, -1));

        txtnik.setLabelText("NIK");
        jPanel1.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 88, 230, -1));

        txtemail.setLabelText("Email");
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 152, 230, -1));

        txtnotelp.setLabelText("No Telpon");
        jPanel1.add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 214, 230, -1));

        txttgllahir.setLabelText("Tanggal Lahir");
        jPanel1.add(txttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 276, 230, -1));

        txtjabatan.setLabelText("Jabatan");
        jPanel1.add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 341, 230, -1));

        btnpilihfoto.setText("Pilih Foto");
        btnpilihfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihfotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnpilihfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 160, -1, 36));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, 36));

        labelfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 220, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiduserActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void btnpilihfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihfotoActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(labelfoto.getWidth(), labelfoto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            labelfoto.setIcon(ic);
            this.filename = f.getAbsolutePath();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnpilihfotoActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String newpath = "src/apk.makost.upload";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdirs();}
            File fileawal = null;
            File fileakhir = null;
            String ext = this.filename.substring(filename.lastIndexOf('.')+1);
            fileawal = new File(filename);
            fileakhir = new File(newpath+"/"+txtnik.getText()+"."+ext);
            System.out.println(fileakhir);
            String sql = "UPDATE tbl_user SET username='"+txtun.getText()+"', password='"+txtpw.getText()+"',"
                    + " nama_depan='"+txtnadep.getText()+"', nama_belakang='"+txtnabel.getText()+"', "
                    + "nama_hewan='"+txthewan.getText()+"', no_telepon='"+txtnotelp.getText()+"', email='"+txtemail.getText()+"',"
                    + " tanggal_lahir='"+txttgllahir.getText()+"', hak_akses='"+txtjabatan.getText()+"',"
                    + " nik='"+txtnik.getText()+"', hobi='"+txthobi.getText()+"', alamat='"+txtalamat.getText()+"', "
                    + "foto ='"+fileakhir.toString()+"' WHERE id_user='"+txtiduser+"'";
            java.sql.Connection conn = (Connection)apk.makost.koneksi.Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Foto Berhasil Tersimpan");
            
            Files.copy(fileawal.toPath(), fileakhir.toPath());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpilihfoto;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelfoto;
    private apk.makost.swing.TextField txtalamat;
    private apk.makost.swing.TextField txtemail;
    private apk.makost.swing.TextField txthewan;
    private apk.makost.swing.TextField txthobi;
    private apk.makost.swing.TextField txtiduser;
    private apk.makost.swing.TextField txtjabatan;
    private apk.makost.swing.TextField txtnabel;
    private apk.makost.swing.TextField txtnadep;
    private apk.makost.swing.TextField txtnik;
    private apk.makost.swing.TextField txtnotelp;
    private apk.makost.swing.TextField txtpw;
    private apk.makost.swing.TextField txttgllahir;
    private apk.makost.swing.TextField txtun;
    // End of variables declaration//GEN-END:variables
}
