/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apk.makost.form;

import apk.makost.model.ModelCard;
import javax.swing.ImageIcon;

/**
 *
 * @author dF
 */
public class Dashboard extends javax.swing.JPanel {

    public Dashboard() {
        initComponents();
        card1.setData(new ModelCard(new ImageIcon(getClass().getResource("/apk/makost/icon/penghuni.png")),"Penghuni","10",""));
        card2.setData(new ModelCard(new ImageIcon(getClass().getResource("/apk/makost/icon/kamar.png")),"Kamar","5",""));
        card3.setData(new ModelCard(new ImageIcon(getClass().getResource("/apk/makost/icon/mkamar.png")),"Ruangan Dihuni","3",""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        card1 = new apk.makost.component.Card();
        card2 = new apk.makost.component.Card();
        card3 = new apk.makost.component.Card();
        roundPanel3 = new apk.makost.swing.RoundPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        roundPanel5 = new apk.makost.swing.RoundPanel();
        roundPanel4 = new apk.makost.swing.RoundPanel();

        setBackground(new java.awt.Color(243, 246, 251));
        setForeground(new java.awt.Color(243, 246, 251));

        panel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        card1.setColor1(new java.awt.Color(242, 140, 251));
        card1.setColor2(new java.awt.Color(204, 96, 168));
        panel.add(card1);

        card2.setColor1(new java.awt.Color(140, 184, 251));
        card2.setColor2(new java.awt.Color(97, 156, 245));
        panel.add(card2);

        card3.setColor1(new java.awt.Color(250, 179, 156));
        card3.setColor2(new java.awt.Color(255, 148, 112));
        panel.add(card3);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayout(new java.awt.GridLayout(2, 0, 0, 12));

        roundPanel5.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jLayeredPane1.add(roundPanel5);

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jLayeredPane1.add(roundPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1)
                        .addGap(18, 18, 18)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private apk.makost.component.Card card1;
    private apk.makost.component.Card card2;
    private apk.makost.component.Card card3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane panel;
    private apk.makost.swing.RoundPanel roundPanel3;
    private apk.makost.swing.RoundPanel roundPanel4;
    private apk.makost.swing.RoundPanel roundPanel5;
    // End of variables declaration//GEN-END:variables
}
